name: Surkeha Hospital Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
              su - surekha -c '
                export NVM_DIR="$HOME/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                
                cd /var/www/surekha-backend
                git remote set-url origin https://Raghavendra-Reddy-Padala:'"$GH_TOKEN"'@github.com/Raghavendra-Reddy-Padala/surekha-wt-backed.git
                git fetch --all
                git reset --hard origin/main
                npm install --production
                pm2 restart hospital-api || pm2 start server.js --name "hospital-api"
                pm2 save
              '